[package]
name = "os"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bitflags = "2.3.3"
multiboot2 = "0.15.1"
strum = { version = "0.25.0", default-features = false }
strum_macros = "0.24.3"
