# github workflow for running `just iso` on push

name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - uses: extractions/setup-just@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y xorriso grub-common qemu-system qemu-utils grub-pc binutils-i686-linux-gnu nasm

      - name: Build ISO
        run: just iso

      - name: Write Git commit into file
        run: echo ${{ github.sha }} > commit

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: ISO
          path: |
            os.iso
            commit
